# Effect presets are defined in presets.toml
# The following parameters are available for presets

# name = Preset name, will be displayed in the GUI
# pitch_value = The pitch value of the preset, if you want to be able to adjust this use "scale"
# downsample_amount = The amount of downsampling to do, set as "none" if you don't want any
# override_pitch_slider = Whether the preset overrides the pitch slider or not

[[presets]]
name = "Man"
pitch_value = "-1.5"
downsample_amount = "none"
override_pitch_slider = true

[[presets]]
name = "Woman"
pitch_value = "2.5"
downsample_amount = "none"
override_pitch_slider = true

[[presets]]
name = "Boy"
pitch_value = "1.25"
downsample_amount = "none"
override_pitch_slider = true

[[presets]]
name = "Girl"
pitch_value = "2.8"
downsample_amount = "none"
override_pitch_slider = true

[[presets]]
name = "Darth\nVader"
pitch_value = "-6"
downsample_amount = "none"
override_pitch_slider = true

[[presets]]
name = "Chipmunk"
pitch_value = "10.0"
downsample_amount = "none"
override_pitch_slider = true

[[presets]]
name = "Russian Mic"
pitch_value = "scale"
downsample_amount = "8"
override_pitch_slider = false
volume_boost = "8"

[[presets]]
name = "Radio"
pitch_value = "scale"
downsample_amount = "6"
override_pitch_slider = false
volume_boost = "5"

[[presets]]
name = "Megaphone"
pitch_value = "scale"
downsample_amount = "2"
override_pitch_slider = false
volume_boost = "8"

[[presets]]
name = "Custom"
pitch_value = "scale"
downsample_amount = "none"
override_pitch_slider = false
